Integrate Accelerate, Deepspeed
Adamliu1/SNLP_GCW pull request #117
Opened 2024-07-09 17:05 UTC by Adamliu1

Partial Fix for #115, #115 will be deprecated, tasks inside #115 will be split into multiple PRs.

This PR contains code for issues issue #105 #113

Here are the following todos and changes made:
- [x] Integrate Accelerator (commented out bf16 currently, can be used as an argument in the future, so far, using full precision)
- [x] Fix model saving after distributed training
- [ ] Fix logging, including default logging and wandb. But use Accelerator's wrapper
  - [ ] wandb
  - [ ] logging (still not working) 
- [x] Currently commented out mink

2024-07-29 14:46 UTC, Davidyz requested changes

2024-07-29 14:46 UTC, Davidyz commented on llm_unlearn_ucl/unlearn_harm.py
> +    if bool(args.wandb_log) and accelerator.is_local_main_process:
The uploading of dataset samples should go [here](https://github.com/Adamliu1/SNLP_GCW/blob/380f2e755a7893f77a80c8adab6d4f461d2a2c1e/llm_unlearn_ucl/data_utils.py#L66), as suggested in #106 .

2024-08-23 11:42 UTC, TheRootOf3 commented on llm_unlearn_ucl/logger_utils.py
> +    wandb_tracker.log_artifact(data_sample_artifacts)
I am unsure if we still need this in the codebase, given we never used those logs (they were supposed for reproducibility) and it adds additional processing time per batch. 

Maybe let's remove?

2024-08-23 11:51 UTC, TheRootOf3 requested changes
good job, comments left 🫡

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +# def compute_mink_prob(
Please remove, we no longer need it. In the worst case we will look back in git history :)

🎶For the first time in **history**
It's gonna start raining men (Start raining men)! 🎶

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +    # # Calculate min-k% prob score on bad_batch using the unmodified pre-trained model
Same here, please remove.

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +                # "ratio (bad) mink unlearning/reference": np.mean(mink_probs_after_step)
please remove.

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +        # f"ratio (bad) mink unlearning/reference: {np.mean(mink_probs_after_step)/np.mean(mink_probs_base):.3f}, "
please remove.

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +        accelerator = Accelerator(log_with="wandb", mixed_precision="bf16")
For visibility: @Willmish's code removes bf16 from the python code and defines it in the deepspeed config.

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +        accelerator = Accelerator(mixed_precision="bf16")
For visibility: @Willmish's code removes bf16 from the python code and defines it in the deepspeed config.

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +            torch_dtype=torch.bfloat16,
For visibility: @Willmish's code removes bf16 from the python code and defines it in the deepspeed config.

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
>              torch_dtype=torch.bfloat16,
For visibility: @Willmish's code removes bf16 from the python code and defines it in the deepspeed config.

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +            torch_dtype=torch.bfloat16,
For visibility: @Willmish's code removes bf16 from the python code and defines it in the deepspeed config.

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
>              torch_dtype=torch.bfloat16,
For visibility: @Willmish's code removes bf16 from the python code and defines it in the deepspeed config.

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +                    # TODO: verify if this implementation is correct
@Adamliu1 ???

2024-08-23 11:51 UTC, TheRootOf3 commented on llm_unlearn_ucl/unlearn_harm.py
> +            # NOTE: here need to verify logic
@Adamliu1, is this sorted?

2024-08-23 16:32 UTC, TheRootOf3 approved these changes
lgtm

2024-08-23 16:33 UTC, merged